name: data_collector_catalog
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  # flutter_audio_capture: ^1.1.7 
  permission_handler: ^11.3.1
  firebase_core: ^3.5.0
  firebase_database: ^11.1.3
  flutter_background_service: ^5.0.10
  cron: ^0.6.1
  # health: ^11.1.0
  # notification_listener_service: ^0.3.3
  # flutter_notification_listener: ^1.3.4
  flutter_local_notifications: ^17.2.3
  path_provider: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
